package com.example.baget.ledger;

public enum LedgerCategory {
    CUSTOMER_PAYMENT,
    CUSTOMER_ADVANCE,
    CUSTOMER_REFUND,
    INVOICE_REVENUE,
    APPLY_ADVANCE_TO_INVOICE,
    MATERIAL_PURCHASE,
    OVERHEAD_EXPENSE,
    INTERNAL_TRANSFER_IN,
    INTERNAL_TRANSFER_OUT,
    ADJUSTMENT
}

