ALTER TABLE orders
    ADD COLUMN PublicId VARCHAR(36) DEFAULT NULL;

UPDATE orders
SET PublicId = UUID()
WHERE PublicId IS NULL;

ALTER TABLE orders
    MODIFY COLUMN PublicId VARCHAR(36) NOT NULL UNIQUE;
