ALTER TABLE orders
    MODIFY COLUMN ItemsTotal DECIMAL(12,2) NULL,
    MODIFY COLUMN TaxRate DECIMAL(5,2) NULL,
    MODIFY COLUMN Freight DECIMAL(12,2) NULL,
    MODIFY COLUMN AmountPaid DECIMAL(12,2) NULL,
    MODIFY COLUMN AmountDueN DECIMAL(12,2) NULL,
    MODIFY COLUMN Income DECIMAL(12,2) NULL,
    MODIFY COLUMN TotalCost DECIMAL(12,2) NULL;
